name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: ^2.0.0  # Supabase ke liye
  flutter_dotenv: ^5.1.0    # .env file read karne ke liye

  # UI and Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0 
  google_fonts: ^6.2.1
  intl: ^0.19.0

  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    # Agar koi images ya logo add karna ho toh yahan se comment hata lena:
    #   - assets/images/